import type { NextPage } from 'next';
import { useRef } from 'react';
import Head from 'next/head';
import { Button, Text, Grid, Input } from '@nextui-org/react';

const ComingSoon: NextPage = () => {
  const ref = useRef();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid.Container justify="center">
        <Grid xs={12} md={8} direction="column" justify="center">
          <Grid.Container css={{ p: '2em 0em' }} justify="center">
            <Grid
              css={{ textAlign: 'center' }}
              xs={10}
              md={12}
              justify="center"
            >
              <Text
                h1
                size={60}
                css={{
                  textGradient: '45deg, $blue600 -20%, $pink600 50%',
                }}
                weight="bold"
              >
                Loudmouth
              </Text>
            </Grid>
            <Grid xs={10} md={12} justify="center">
              <Text css={{ textAlign: 'center' }} h1>
                Our Content Builder App Is Almost Ready!
              </Text>
            </Grid>
            <Grid xs={10} md={12} justify="center">
              <Text css={{ textAlign: 'center' }}>
                We&apos;re so happy you enjoyed our keyword scoring app! Our AI
                powered content building app is almost finished. Drop us your
                email and we&apos;ll let you know as soon as we&apos;re ready!
              </Text>
            </Grid>
            <Grid xs={10} md={12} justify="center" css={{ pt: '2em' }}>
              <Grid.Container gap={1}>
                <Grid xs={12} md={8}>
                  <Input
                    bordered
                    labelPlaceholder="Email"
                    color="default"
                    fullWidth
                  />
                </Grid>
                <Grid xs={12} md={4}>
                  <Button color="secondary">Submit</Button>
                </Grid>
              </Grid.Container>
            </Grid>
          </Grid.Container>
        </Grid>
      </Grid.Container>
    </div>
  );
};

export default ComingSoon;
