import type { NextPage } from 'next';
import { useRef } from 'react';
import Head from 'next/head';
import { Button, Text, Grid } from '@nextui-org/react';
import {
  Chart as ChartJS,
  RadialLinearScale,
  ArcElement,
  Tooltip,
  Legend,
} from 'chart.js';
import { PolarArea } from 'react-chartjs-2';
import Link from 'next/link';

ChartJS.register(RadialLinearScale, ArcElement, Tooltip, Legend);

const data = {
  labels: ['Go After These First', 'Build Long Term', 'Not Worth It'],
  responsive: true,
  datasets: [
    {
      label: '# of Votes',
      data: [12, 19, 3],
      backgroundColor: [
        'rgba(54, 162, 235, 0.5)',
        'rgba(255, 206, 86, 0.5)',
        'rgba(255, 99, 132, 0.5)',
      ],
      borderWidth: 1,
    },
  ],
};

const Home: NextPage = () => {
  const ref = useRef();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid.Container
        justify="center"
        css={{
          background: 'no-repeat url(abstract-2.svg)',
          minHeight: '100vh',
        }}
      >
        <Grid xs={12} md={10} direction="column">
          <nav>
            <Grid.Container
              direction="row"
              justify="space-between"
              alignItems="center"
              gap={2}
            >
              <Grid xs={6}>
                <Text
                  h1
                  size={35}
                  css={{
                    textGradient: '45deg, $blue600 -20%, $pink600 50%',
                  }}
                  weight="bold"
                >
                  Loudmouth
                </Text>
              </Grid>
              <Grid xs={6} justify="flex-end">
                <Link href="/keywords">
                  <Button color="secondary">Get Started</Button>
                </Link>
              </Grid>
            </Grid.Container>
          </nav>

          <main>
            <Grid.Container
              direction="row"
              justify="space-between"
              gap={2}
              css={{ pt: '5em' }}
            >
              <Grid xs={12} md={6} direction="column">
                <div>
                  <Text h1 css={{ lineHeight: '1.15em' }}>
                    Create your SEO content strategy in minutes.
                  </Text>
                </div>
                <div style={{ padding: '2em 0em' }}>
                  <Text h4>
                    Get a better understanding of what search terms you should
                    put your time into. No agency needed.
                  </Text>
                </div>
                <div>
                  <Link href="/keywords">
                    <Button color="secondary" size="lg">
                      Get Started
                    </Button>
                  </Link>
                </div>
              </Grid>
              <Grid xs={12} md={6} justify="flex-end">
                <PolarArea
                  data={data}
                  style={{ maxWidth: '450px', maxHeight: '450px' }}
                />
              </Grid>
            </Grid.Container>
          </main>
        </Grid>
      </Grid.Container>
    </div>
  );
};

export default Home;
