import type { NextPage } from 'next';
import { useRef } from 'react';
import Head from 'next/head';
import { Button, Text, Grid, Textarea } from '@nextui-org/react';
import Link from 'next/link';

const Keywords: NextPage = () => {
  const ref = useRef();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid.Container justify="center">
        <Grid xs={12} md={10} direction="column" justify="center">
          <Grid.Container css={{ p: '2em 0em' }} justify="center">
            <Grid
              css={{ textAlign: 'center' }}
              xs={10}
              md={12}
              justify="center"
            >
              <Text
                h1
                size={60}
                css={{
                  textGradient: '45deg, $blue600 -20%, $pink600 50%',
                }}
                weight="bold"
              >
                Loudmouth
              </Text>
            </Grid>
            <Grid xs={10} md={12} justify="center">
              <Text css={{ textAlign: 'center' }} h1>
                Let&apos;s get started. Enter your keywords.
              </Text>
            </Grid>
            <Grid xs={10} md={12} justify="center">
              <Text css={{ textAlign: 'center' }}>
                Need help getting keywords? Go to{' '}
                <a href="https://ads.google.com/home/tools/keyword-planner/">
                  https://ads.google.com/home/tools/keyword-planner/
                </a>{' '}
                to explore keywords that make sense for your business.
              </Text>
            </Grid>
            <Grid xs={12} justify="center" css={{ pt: '2.5em' }}>
              <Grid.Container justify="center">
                <Grid xs={11} sm={8} justify="center">
                  <Textarea
                    width="90%"
                    minRows={10}
                    placeholder="Paste your terms here (comma separated)"
                  />
                </Grid>
              </Grid.Container>
            </Grid>
            <Grid xs={12} justify="center" css={{ pt: '2.5em' }}>
              <Link href="/results">
                <Button color="secondary" size="xl">
                  Submit Keywords
                </Button>
              </Link>
            </Grid>
          </Grid.Container>
        </Grid>
      </Grid.Container>
    </div>
  );
};

export default Keywords;
